### ISSUE TITLE
Bug With History Feature - Life Totals always 1 lower in history

### ISSUE THREAD

**Issue by MatthewTompkins0804** [birkoss/mtg-tracker#1]
When looking at the history feature, life totals show as 1 lower than in reality. For example when losing 10 life and going from 40 to 30, the history will show that player as having gone from 39 to 29. Losing all of your life shows up as 39 to -1 rather than 40 to 0.

Additionally, there’s no way to clear the history between games from what I can tell. It does clear when forcibly closing the application and reopening it however. How I’d potentially implement that is a way to manually clear history as well as an option to clear history every time a new game is started. That way in a tournament setting there’s no confusion as to which part of history is the game you’re currently playing and which was the previous game you’re playing.

**Comment by birkoss** [comment]
I fixed the -1 issue, it will be available on the next release.

I'll add a button to manually clear the history and a new settings to clear it after new game (it will be disable by default). I'll be able to complete this today, and I'll see when I can test and release it.

Thanks for the report and suggestions!

**Comment by MatthewTompkins0804** [comment]
New features look great and I can confirm that the -1 bug is fixed. Some feedback on the manual clear history button is there’s no confirmation prompt when deleting history manually. In a situation where a judge would need to review this page it could cause problems if it was accidentally (or even intentionally for unsavory types!) cleared. Very minor issue overall, I still think it’s great as is. Hope this feedback helps!

**Comment by birkoss** [comment]
Yeah, once I published the last release, I noted to add a confirmation.

It's done (and I also fixed another minor issue I had encounter on a previous game.

I'm publishing the new version, should be available soon.

Thanks again for this. It's really motivating for a developer to receive any kind of feedback!
